# -*- coding: utf-8 -*-

"""
Enumerations utilisées pour les calculs de la redevance domaniale.
"""

__all__ = [
    'Commune',
    'Temporalite',
    'TypesNatureEmprise',
    'UnitesDuree',
    'ZoneDomPrive',
    'ZoneLotAgricole',
    'ZonesOccupations'
    ]


from openfisca_pf.base import Enum


class Commune(Enum):
    """
    Communes associées de Polynésie Française
    """
    com111 = 'ANAA'
    com112 = 'FAAITE'
    com120 = 'ARUE'
    com132 = 'ARUTUA'
    com131 = 'APATAKI'
    com133 = 'KAUKURA'
    com141 = 'ANAU'
    com142 = 'FAANUI'
    com143 = 'NUNUE'
    com150 = 'FAAA'
    com161 = 'FAKARAVA'
    com162 = 'KAUEHI'
    com163 = 'NIAU'
    com172 = 'FANGATAU'
    com171 = 'FAKAHINA'
    com180 = 'FATU-HIVA'
    com190 = 'GAMBIER'
    com202 = 'HAO'
    com201 = 'AMANU'
    com203 = 'HEREHERETUE'
    com211 = 'HIKUERU'
    com212 = 'MAROKAU'
    com221 = 'HITIAA'
    com222 = 'MAHAENA'
    com223 = 'PAPENOO'
    com224 = 'TIAREI'
    com231 = 'ATUONA'
    com232 = 'PUAMAU'
    com241 = 'FAIE'
    com242 = 'FARE'
    com243 = 'FITII'
    com244 = 'HAAPU'
    com245 = 'MAEVA'
    com246 = 'MAROE'
    com247 = 'PAREA'
    com248 = 'TEFARERII'
    com250 = 'MAHINA'
    com262 = 'MAKEMO'
    com261 = 'KATIU'
    com263 = 'RAROIA'
    com264 = 'TAENGA'
    com272 = 'MANIHI'
    com271 = 'AHE'
    com280 = 'MAUPITI'
    com291 = 'AFAREAITU'
    com292 = 'HAAPITI'
    com293 = 'MAIAO'
    com294 = 'PAOPAO'
    com295 = 'PAPETOAI'
    com296 = 'TEAVARO'
    com301 = 'NAPUKA'
    com302 = 'TEPOTO-NORD'
    com311 = 'HATIHEU'
    com312 = 'TAIOHAE'
    com313 = 'TAIPIVAI'
    com321 = 'NUKUTAVAKE'
    com322 = 'VAHITAHI'
    com323 = 'VAIRAATEA'
    com330 = 'PAEA'
    com340 = 'PAPARA'
    com350 = 'PAPEETE'
    com360 = 'PIRAE'
    com370 = 'PUKAPUKA'
    com380 = 'PUNAAUIA'
    com391 = 'ANATONU'
    com392 = 'RAIRUA-MAHANATOA'
    com393 = 'VAIURU'
    com403 = 'RANGIROA'
    com401 = 'MAKATEA'
    com402 = 'MATAIVA'
    com404 = 'TIKEHAU'
    com410 = 'RAPA'
    com422 = 'REAO'
    com421 = 'PUKARUA'
    com431 = 'AMARU'
    com432 = 'ANAPOTO'
    com433 = 'MUTUAURA'
    com441 = 'AVERA (RURUTU)'
    com442 = 'HAUTI'
    com443 = 'MOERAI'
    com451 = 'FAAAHA'
    com452 = 'HAAMENE'
    com453 = 'HIPU'
    com454 = 'IRIPAU'
    com455 = 'NIUA'
    com456 = 'RUUTIA'
    com457 = 'TAPUAMU'
    com458 = 'VAITOARE'
    com460 = 'TAHUATA'
    com471 = 'AFAAHITI'
    com472 = 'FAAONE'
    com473 = 'PUEU'
    com474 = 'TAUTIRA'
    com481 = 'TEAHUPOO'
    com482 = 'TOAHOTU'
    com483 = 'VAIRAO'
    com492 = 'TAKAROA'
    com491 = 'TAKAPOTO'
    com501 = 'AVERA (RAIATEA)'
    com502 = 'OPOA'
    com503 = 'PUOHINE'
    com510 = 'TATAKOTO'
    com521 = 'MATAIEA'
    com522 = 'PAPEARI'
    com531 = 'MAHU'
    com532 = 'MATAURA'
    com533 = 'TAAHUAIA'
    com541 = 'FETUNA'
    com542 = 'TEHURUI'
    com543 = 'TEVAITOA'
    com544 = 'VAIAAU'
    com550 = 'TUREIA'
    com560 = 'UA-HUKA'
    com571 = 'HAKAHAU'
    com572 = 'HAKAMAII'
    com580 = 'UTUROA'


class Temporalite(Enum):
    Journalier = 'Journalier'
    Hebdomadaire = 'Hebdomadaire'
    Mensuel = 'Mensuel'
    Annuel = 'Annuel'
    Non_Applicable = 'Non Applicable'


class TypesNatureEmprise(Enum):
    # Tarif de type_1 (calcul de type part_fixe + part_unitaire * nombre_element + part_surfacique * surface)
    ip_eco_01_equipement_pays = 'IP-ECO-01 Equipement du Pays'
    ip_eco_08_centre_artisanaux_aero = 'IP-ECO-08 Centre artisanaux (zone aéroportuaire)'
    ip_eco_09_infra_restauration_tourisme = 'IP-ECO-09 Infrastructure de restauration (sites touristiques)'
    ip_eco_10_boutique_vente_tourisme = 'IP-ECO-10 Boutiques de vente (sites touristiques)'
    ip_eco_11_support_embarcation_legere = 'IP-ECO-11 Support pour embarcation légère'
    co_eco_01_bati = 'CO-ECO-01 Bâti (cas général)'
    co_eco_03_ouvrage_rehabilitation = 'CO-ECO-03 Ouvrage de réhabilitation'
    co_eco_04_bati_perli = 'CO-ECO-04 Bâti pour la perliculture et l aquaculture'
    em_eco_05_emprise_maririme_general = 'EM-ECO-05 Emprise maritime ou terrestre (cas général)'
    em_eco_06_emprise_maritime_lucratif = 'EM-ECO-06 Emprise dédiée à une activité nautique lucrative'
    em_eco_08_emprise_eco_tourisme = 'EM-ECO-08 Emprise éco-touristique'
    em_eco_09_activite_agricole_aero = 'EM-ECO-09 Activités agricoles (zone aéroportuaire)'
    im_eco_06_activite_resto_mobile_aero = 'IM-ECO-06 Activités de restauration mobiles (zone aéroportuaire)'
    im_eco_08_autres_lucrative = 'IM-ECO-08 Autres activités lucratives  (zone aéroportuaire)'
    im_eco_10_activite_non_lucrative_inf_trim = 'IM-ECO-10 Activité à but non lucratif de moins de 3 mois'
    if_eco_03_operu_hors_passe = 'IF-ECO-03 Peche: Parc à Operu (Zone Hors passe)'
    if_eco_04_operu_passe = 'IF-ECO-04 Peche: Parc à Operu (Zone passe)'
    if_eco_05_aquaculture_lagon = 'IF-ECO-05 Aquaculture (hors perliculture) en lagon '
    if_eco_06_aquaculture_canalisation = 'IF-ECO-06 Aquaculture : canalisations'
    if_eco_07_aquaculture_mer = 'IF-ECO-07 Aquaculture (hors perliculture) en haute mer '
    if_eco_08_perliculture_collectage = 'IF-ECO-08 Perliculture collectage'
    if_eco_09_perliculture_elevage = 'IF-ECO-09 Perliculture élevage'
    if_eco_10_canalisation_publique = 'IF-ECO-10 Canalisations publiques, SWAC, OSMOSER'
    if_eco_11_canalisation_secteur_prim = 'IF-ECO-11 Canalisations secteur primaire'
    if_eco_12_canalisation_secteur_sec = 'IF-ECO-12 Canalisations secteurs secondaire et tertiaire'
    if_eco_13_installation_technique = 'IF-ECO-13 Installation technique'
    if_eco_14_support_publicitaire = 'IF-ECO-14 Support publicitaire, comptoir accueil'
    if_eco_16_captage_eau_sousterraine = 'IF-ECO-16 Captage d\'eau souterraine'
    ip_pr_05_support_embarcation_legere = 'IP-PR-05 Support pour embarcation légère'
    co_pr_01_bati = 'CO-PR-01 Bâti (cas général)'
    co_pr_03_ouvrage_rehabilitation = 'CO-PR-03 Ouvrage de réhabilitation'
    co_pr_04_habitation_zone_aero = 'CO-PR-04 Habitation (zone aéropotuaire)'
    em_pr_05_emprise_maririme_general = 'EM-PR-05 Emprise maritime ou terrestre (cas général)'
    em_pr_07_emprise_maritime_non_lucratif = 'EM-PR-07 Emprise maritime ou terrestre non lucrative'
    if_pr_03_support_publicitaire = 'IF-PR-03 Support publicitaire'
    if_pr_02_ancrage_sans_droit = 'IF-PR-02 Ancrage et/ou mouillage sans droit immobilier'
    im_eco_15_vente_couronne_aero = 'IM-ECO-15 Vente de couronnes (zones aéroportuaires)'
    em_eco_10_excursion_tupai = 'EM_ECO_10 Activités d excursion à la journée sur l île de Tupai'
    im_eco_16_autres_activites_aero = 'IM_ECO_16 Autres activités lucratives (à l intérieur de l aérogare)'
    if_eco_18_captage_eau_sousterraine_primaire = 'IF_ECO_18 Captage d eau souterraine pour le secteur primaire'
    if_eco_19_captage_eau_sousterraine_publique = 'IF_ECO_19 Captage d eau souterraine pour une collectivité publiques'
    if_eco_21_captage_eau_surface_secondaire = 'IF_ECO_21 Captage deau de surface pour le secteur secondaire et tertiaire'
    if_eco_22_captage_eau_surface_primaire = 'IF_ECO_22 Captage d eau de surface pour le secteur primaire'
    if_eco_23_captage_eau_surface_publique = 'IF_ECO_23 Captage deau de surface pour une collectivité publiques'
    if_pr_04_captage_eau_sousterraine_privee = 'IF_PR_04 Captage d eau souterraine pour habitation'
    if_pr_05_captage_eau_surface_privee = 'IF_PR_05 Captage d eau de surface pour habitation'

    # Tarif de type_2 (les paramètres du type_1 dépendent de la zone géographique)
    ip_eco_06_infra_restauration_aero = 'IP-ECO-06 Infrastructure de restauration aéroportuaire'
    ip_eco_07_boutique_produit_local_aero = 'IP-ECO-07 Boutique de produit locaux (zone aéroportuaire)'
    co_eco_02_ouvrage_defence = 'CO-ECO-02 Ouvrage d\'aménagement, de défense ou d\'accessibilité'
    em_eco_07_emprise_maritime_prive = 'EM-ECO-07 Emprise maritime privatisée'
    im_eco_01_activite_lucrative_manifestation = 'IM-ECO-01 Activité lucrative annexe à une manifestation sportive'
    im_eco_05_marche_puces = 'IM-ECO-05 Marché aux puces'
    im_eco_07_vente_produit_locaux_aero = 'IM-ECO-07 Vente de produits locaux  (zone aéroportuaire)'
    im_eco_09_vente_etale = 'IM-ECO-09 Vente à l étale'
    im_eco_13_restau_mobile = 'IM-ECO-13 Restauration ambulante'
    if_eco_15_corp_mort = 'IF-ECO-15 Corps-mort, ancrage, mouillage'
    if_eco_17_gestion_corp_mort = 'IF-ECO-17 Activité de gestion des corps-morts et/ou ancrages, mouillage'
    co_pr_02_ouvrage_defence = 'CO-PR-02 Ouvrage d\'aménagement, de défense ou d\'accessibilité'
    em_pr_06_emprise_maritime_prive = 'EM-PR-06 Emprise maritime privatisée'
    if_pr_01_ancrage_avec_droit_immo = 'IF-PR-01 Ancrage et/ou mouillage avec droit immobilier'

    # Tarif de type_3 (calculs selon des paliers sur un tarif journalier dégressif avec la durée d'occupation)
    ip_eco_02_bati_tout_public_ac_elec = 'IP-ECO-02 Bâti à usage tout public avec électricité'
    ip_eco_03_terrain_sport_ac_elec = 'IP-ECO-03 Terrain de sport avec éléctricité'
    ip_eco_04_bati_tout_public_sans_elec = 'IP-ECO-04 Bâti à usage tout public sans électricité'
    ip_eco_05_terrain_sport_sans_elec = 'IP-ECO-05 Terrain de sport sans électricité'
    em_eco_01_espace_pelouse_ac_elec = 'EM-ECO-01 Espace pelouse avec électricité'
    em_eco_02_surface_mineral_ac_elec = 'EM-ECO-02 Surface minéralisée avec électricité'
    em_eco_03_espace_pelouse_sans_elec = 'EM-ECO-03 Espace pelouse sans électricité'
    em_eco_04_surface_mineral_sans_elec = 'EM-ECO-04 Surface minéralisée sans électricité'
    im_eco_11_activite_lucrative_inf_trim = 'IM-ECO-11 Activité à but lucratif de moins de 3 mois'
    im_eco_12_activite_alim_lucrative_inf_trim = 'IM-ECO-12 Activité alimentaire à but lucratif de moins de 3 mois'
    ip_pr_01_bati_tout_public_ac_elec = 'IP-PR-01 Bâti à usage tout public avec électricité'
    ip_pr_02_terrain_sport_ac_elec = 'IP-PR-02 Terrain de sport avec électricité'
    ip_pr_03_bati_tout_public_sans_elec = 'IP-PR-03 Bâti à usage tout public sans électricité'
    ip_pr_04_terrain_sport_sans_elec = 'IP-PR-04 Terrain de sport sans électricité'
    em_pr_01_espace_pelouse_ac_elec = 'EM-PR-01 Espace pelouse avec électricité'
    em_pr_02_surface_mineral_ac_elec = 'EM-PR-02 Surface minéralisée avec électricité'
    em_pr_03_espace_pelouse_sans_elec = 'EM-PR-03 Espace pelouse sans électricité'
    em_pr_04_surface_mineral_sans_elec = 'EM-PR-04 Surface minéralisée sans électricité'

    # Tarif de type_4 (les paramètres du type_3 dépendent de la zone géographique)
    im_eco_02_foire_produit_locaux = 'IM-ECO-02 Foire de produits locaux'
    im_eco_03_foire_commerciale = 'IM-ECO-03 Foire commerciale'
    im_eco_04_activite_ludique = 'IM-ECO-04 Activité ludique'
    im_eco_14_foire_locaux_agricoles = 'IM-ECO-14 Foire de produits locaux agricoles'

    # Tarif de type_5 (calcul par pallier de surface)
    if_eco_01_parc_poisson_hors_passe = 'IF-ECO-01 Pêche : Parc à poissons et viviers (Zone hors passe)'
    if_eco_02_parc_poisson_passe = 'IF-ECO-02 Pêche : Parc à poissons et viviers (Zone passe)'

    # Tarif Type_7 (indépendant de la durée) i.e extraction
    ex_eco_01_dpf_hors_entite_publique = 'EX-ECO-01 Domaine public fluvial Hors entité publique'
    ex_eco_02_dpf_pour_entite_publique = 'EX-ECO-02 Domaine public fluvial pour entité publique'
    ex_eco_03_dpm_hors_entite_publique = 'EX-ECO-03 Domaine public maritime Hors entité publique'
    ex_eco_04_dpm_pour_entite_publique = 'EX-ECO-04 Domaine public maritime Pour entité publique'
    ex_eco_05_dprive = 'EX-ECO-05 Domaine public privé'

    # Tarif Type _8 (Zonage en 5 zone)
    ag_priv_01_maraichage = 'AG-PRIV-01 Agriculture de type maraîchère, vivière, fruitière'
    ag_priv_02_elevage = 'AG-PRIV-02 Elevage'
    ag_priv_03_coprah = 'AG-PRIV-03 Coprah-Culture'
    ag_priv_04_agroforesterie = 'AG-PRIV-04 Agro-foresterie'
    ag_priv_05_agrotransformation = 'AG-PRIV-05 Agro-transformation'

    # Nature d'emprise pour le domaine privé (location)
    priv_01_touristique = 'PRIV-01 Aménagement touristique'
    priv_02_eco_industriel = 'PRIV-02 Opération économique ou industrielle'
    priv_03_projet_social = 'PRIV-03 Projet à caractère social, éducatif ou sportif'
    priv_04_etablissement_public = 'PRIV-04 Location au profit des établissements publics pour les besoins de leur fonctionnement '
    priv_05_habitat_social = 'PRIV-05 Habitat social'
    priv_06_developpement_durable = 'PRIV-06 Développement durable'
    priv_07_technologie_information = 'PRIV-07 Activités liées aux technologies, contenus et support de l information'
    priv_08_cultuel = 'PRIV-08 Projet à caractère cultuel'
    priv_09_autres = 'PRIV-09 Autre occupation'

    # Tarif Type_10 lotissements agricoles
    ag_priv_06_lot_agricole = 'AG-PRIV-06 Location sur lotissement Agricole'


class UnitesDuree(Enum):
    Heures = 'Heures'
    Jours = 'Jours'
    Mois = 'Mois'
    Annees = 'Années'


class ZoneDomPrive(Enum):
    """
    Ensemble des noms de zones de l'arrêté 136CM
    """
    village = 'Village'
    secteur = 'Secteur'
    zone_de_base = 'Zone de base'
    zone_bord_de_mer = 'Zone bord de mer'
    zone_cote_mer = 'Zone cote mer'
    zone_plaines_et_basses_montagnes = 'Zone plaines et basses montagnes'
    zone_moyennes_montagnes = 'Zone moyennes montagnes'
    zone_rurale = 'Zone rurale'
    zone_touristique = 'Zone touristique'
    motu = 'Motu'
    centre_ville = 'Centre-ville'
    zone_hautes_montagnes = 'Zone hautes montagnes'
    tetamanu = 'TETAMANU'
    village_zone_rurale = 'Village (zone rurale)'
    zone_montagne = 'Zone montagne'
    zone_habitation = 'Zone d\'habitation'
    zone_habitat = 'Zone d\'habitat'
    zone_agricole_motu = 'Zone agricole motu'
    zone_montagneuse = 'Zone montagneuse'
    bord_de_mer = 'Bord de mer'
    cote_montagne = 'Cote montagne'
    domaine_opunohu = 'Domaine Opunohu'
    vaiare_bord_de_mer = 'Vaiare Bord de mer'
    vaiare_cote_montagne = 'Vaiare Cote montagne'
    temae_bord_de_mer = 'Temae Bord de mer'
    temae_cote_montagne = 'Temae Cote montagne'
    temae_bel_air = 'Temae Residence Bel Air'
    taunoa_zone_urbaine = 'Taunoa - Zone urbaine à forte densite de population'
    taunoa_zone_bord_de_mer = 'Taunoa - Zone bord de mer'
    mamao_zone_commercial = 'Mamao - Zone commercial et d\'habitat'
    titioro_zone_industrielle_et_commerciale = 'Titioro - Zone industrielle et commerciale'
    titioro_zone_habitat = 'Titioro - Zone habitat'
    paofai_zone_plaine = 'Paofai - Zone commerciale (plaine)'
    paofai_zone_montagne = 'Paofai - Zone d\'habitat (montagne)'
    sainte_amelie_zone_habitat = 'Sainte Amelie - Zone d’habitat'
    sainte_amelie_quartier_des_institutions = 'Sainte Amelie - Quartier des institutions (quartier broche)'
    tipaerui_zone_industrielle_et_commerciale = 'Tipaerui - Zone industrielle et commerciale'
    tipaerui_zone_residentielle = 'Tipaerui - Zone residentielle'
    tipaerui_zone_sociale = 'Tipaerui - Zone sociale'
    motu_et_bord_de_mer = 'Motu et bord de mer'
    zone_habitat_village = 'Zone d\'habitat village'
    zone_rurale_montagneuse = 'Zone rurale montagneuse'
    zone_rurale_plaine = 'Zone rurale plaine'
    village_hors_bord_de_mer = 'Village (hors bord de mer)'
    bord_de_mer_et_bord_de_route = 'Bord de mer et bord de route'
    bord_de_route = 'Bord de route'
    zone_de_lotissement = 'Zone de lotissement'
    zone_hors_lotissement = 'Zone hors lotissement'


class ZoneLotAgricole(Enum):
    """
    Ensemble des lotissements agricoles
    """
    amo = 'AMO'
    atimaono_1 = 'ATIMAONO 1'
    atimaono_2 = 'ATIMAONO 2'
    marumarutua_1_15 = 'MARUMARUTUA - Lot 1 à 15'
    marumarutua_16_22 = 'MARUMARUTUA - Lot 16 à 22'
    plateau_taravao_1_6 = 'PLATEAU TARAVAO - Lot 1 à 6'
    plateau_taravao_7_20 = 'PLATEAU TARAVAO - Lot 7 à 20'
    plateau_taravao_extension = 'PLATEAU TARAVAO EXTENSION'
    plateau_taravao_extension_2 = 'PLATEAU TARAVAO EXTENSION 2'
    rose = 'ROSE'
    socredo_1 = 'SOCREDO - à mettre à jour'
    socredo_2_4 = 'SOCREDO - Lot 2, 3, 4'
    vaitepiha = 'VAITEPIHA'
    opunohu = 'OPUNOHU'
    opunohu_rive_gauche = 'OPUNOHU RIVE GAUCHE'
    rotui = 'ROTUI'
    vaianae = 'VAIANAE'
    opoa = 'OPOA'
    faaroa_agri = 'FAAROA - lots à des fins agricoles'
    faaroa_elevage = 'FAAROA - 143b, 199, 200 et 201 (lots à des fins d\'élevage)'
    maraeroa = 'MARAEROA'
    tarodiere_opoa = 'TARODIERE OPOA'
    bachelier = 'BACHELIER'
    hamoa = 'HAMOA'
    faahue = 'FAAHUE'
    matavahi_1 = 'MATAVAHI 1'
    matavahi_2 = 'MATAVAHI 2'
    metuarii = 'METUARII'
    atai = 'ATAI'
    terre_deserte = 'TERRE DESERTE'
    taipivai = 'TAIPIVAI'
    hiniaehi = 'HINIAEHI'


class ZonesOccupations(Enum):
    """
    Le zonnage dépend des activitées.
    Le zonnage basic est calculé comme le prix moyen des terrain en bord de mer.
    Le zonnage secondaire dépend de la fréquentaion aeroportuaire.
    Le dernier zonnage corresponds aux archipels
    """
    zone_1 = 'Zone 1'
    zone_2 = 'Zone 2'
    zone_3 = 'Zone 3'
    zone_4 = 'Zone 4'
    zone_5 = 'Zone 5'
