from openfisca_core.model_api import Enum

class DomaineActivite(Enum):
    EXON_SOCIETES_EXPORTATRICES = "EXON. SOCIETES EXPORTATRICES"
    SOCIETES_MINIERES = "SOCIETES MINIERES"
    ETABTS_FINANCIERS_CREDIT_BAIL = "ETABTS FINANCIERS, CREDIT-BAIL"
    SOCIETES_GEST_FONDS_GARANTIE = "SOCIETES DE GEST. FONDS GARANTIE"
    GIE_SCPR_SCM_EXON = "GIE, SCPR, SCM - EXON"
    EXON_ACTIVITES_CROISIERE = "EXON. ACTIVITES DE CROISIERE"
    EXON_CROISIERE_MIXTE = "EXON. CROISIERE MIXTE"
    ENERGIES_RENOUVELABLES = "ENERGIES RENOUVELABLES"
    EXON_HOTEL_RES_INTERNATIONAL = "EXON. HOTEL/RES. INTERNATIONAL"
    EXON_CONCESSIONS_MINIERES = "EXON. CONCESSIONS MINIERES"
    SECTEUR_NUMERIQUE = "SECTEUR NUMERIQUE"
    SECT_RECHERCHE_DEVELOPPEMENT = "SECT RECHERCHE DEVELOPPEMENT"
    EXON_ORGA_A_BUT_NON_LUCRATIF = "EXON. ORGA. A BUT NON LUCRATIF"
    NON_REDEVABLE_MEMBRE_GROUPE_FISCAL = "NON-REDEVABLE (MEMBRE GROUPE FISCAL)"
    ZONE_REVITALISATION_ACTIVITES_ECO_ZRAE = "ZONE REVITALISATION ACTIVITES ECO ZRAE"
