FROM python:3.7-slim AS build

# ENV PATH="/opt/venv/bin:$PATH"

COPY docker/install_deps /install_deps
COPY docker/variables.patch /variables.patch
RUN /install_deps


WORKDIR /openfisca-pf
# RUN pip install --editable .[dev]



EXPOSE 5000/tcp

CMD ["openfisca", "serve", "--configuration-file", "config.py"]
