#!/bin/bash -xe

apt-get update
apt-get install -y --no-install-recommends build-essential gcc git
pip install --upgrade pip
pip install python-dateutil

if [[ "$1" == "--test" ]]
then
   pip install --no-cache-dir flake8 pytest
fi

git clone --depth 1 --branch 40.0.0 https://github.com/openfisca/openfisca-core.git
cd openfisca-core
sed -i s/float32/float64/ openfisca_core/variables/config.py
sed -i s/float32/float64/ openfisca_core/tools/__init__.py

if [[ "$1" != "--test" ]]
then
  patch -t -d openfisca_web_api/loader < variables.patch
else
  sed -i s/float32/float64/ tests/core/tools/test_runner/test_yaml_runner.py
fi

pip install --no-cache-dir wheel
pip install --no-cache-dir .
