name: Publish Docker images

on:
  push:
    branches: 
      - 'master'
      - 'develop'
      - 'feature/*'
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: python:3.11
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4.2.2
    -
      name: Dependencies
      run: docker/install_deps --test
    -
      name: Build
      run: make build
    -
      name: Test
      run: make test

  build:
    runs-on: ubuntu-20.04
    needs: test
    env:
      repo: "govpf/openfisca-pf"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4.2.2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.10.0
    -
      name: Login to DockerHub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push (master)
      uses: docker/build-push-action@v6.14.0
      if: github.ref == 'refs/heads/master'
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:latest
    -
      name: Extract tag name
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> ${GITHUB_OUTPUT}
      id: extract_tag
    -
      name: Build and push (tags)
      uses: docker/build-push-action@v6.14.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:${{ steps.extract_tag.outputs.tag }}
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v4.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"
