name: Publish Docker images

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2.3.4
    -
      name: Dependencies
      run: docker/install_deps --test
    -
      name: Build
      run: make build
    -
      name: Test
      run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      repo: "govpf/openfisca-pf"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2.3.4
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push (master)
      uses: docker/build-push-action@v2.10.0
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:latest
    -
      name: Extract tag name
      if: github.event_name == 'push' && github.ref != 'refs/heads/master'
      shell: bash
      run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      id: extract_tag
    -
      name: Build and push (tags)
      uses: docker/build-push-action@v2.10.0
      if: github.event_name == 'push' && github.ref != 'refs/heads/master'
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:${{ steps.extract_tag.outputs.tag }}
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v2.4.3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"
