name: Publish Docker images

on:
  push:
    branches: 
      - 'master'
      - 'develop'
      - 'feature/*'
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: python:3.7
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3.2.0
    -
      name: Dependencies
      run: docker/install_deps --test
    -
      name: Build
      run: make build
    -
      name: Test
      run: make test

  build:
    runs-on: ubuntu-20.04
    needs: test
    env:
      repo: "govpf/openfisca-pf"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3.2.0
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.5.0
    -
      name: Login to DockerHub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: remove / in branch name (not master - not tag)
      uses: mad9000/actions-find-and-replace-string@3
      if: github.event_name == 'push' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop' && github.ref != 'refs/tags'
      id: findandreplace
      with:
        source: ${{ github.ref }}
        find: 'refs/heads/feature/'        
        replace: 'feature_'
    -
      name: Build and push (not master - not develop -  not tag)
      uses: docker/build-push-action@v4.0.0
      if: github.event_name == 'push' && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/develop'  && github.ref != 'refs/tags'
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:${{ steps.findandreplace.outputs.value }}
    -
      name: Build and push (develop)
      uses: docker/build-push-action@v4.0.0
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:develop
    -
      name: Build and push (master)
      uses: docker/build-push-action@v4.0.0
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:latest
    -
      name: Extract tag name
      if: github.event_name == 'push' && github.ref == 'refs/tags'
      shell: bash
      run: echo "##[name=tag;]$(echo ${GITHUB_REF#refs/tags/} ${GITHUB_OUTPUT})"
      id: extract_tag
    -
      name: Build and push (tags)
      uses: docker/build-push-action@v4.0.0
      if: github.event_name == 'push' && github.ref == 'refs/tags'
      with:
        context: .
        file: ./docker/Dockerfile
        platforms: linux/amd64
        pull: true
        push: true
        tags: |
          ${{ env.repo }}:${{ steps.extract_tag.outputs.tag }}
    - name: Update repo description
      uses: peter-evans/dockerhub-description@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: "${{ env.repo }}"
